#you can access the endpoints using : http://localhost:9000
version: '3'
services:
  # octopusx console service
  console:
    image: ekoopensource/octopusx-console:v1.0
    ports:
      - "5009:8080"
    env_file:
      - .env

  # octopusx access service
  access:
    image: ekoopensource/octopusx-access:v1.9
    ports:
      - "5001:55504"
    depends_on:
      - data
    links:
      - data:data_host_url

  # octopusx auth service
  auth:
    image: ekoopensource/octopusx-auth:v1.1
    ports:
      - "5002:55501"
  profile:
    image: ekoopensource/octopusx-profile:v1.01
    ports:
      - "5003:55503"

  # octopusx data service
  data:
    container_name: octopusx_data
    image: ekoopensource/octopusx-data:v1.0
    ports:
      - "5004:55505"
    depends_on:
      - octopusx_db
    links:
      - octopusx_db:database

  # MySQL and document data store
  octopusx_db:
    container_name: octopusx_db
    image: mysql:5.7
    ports:
      - "30030:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: NULL
      MYSQL_DATABASE: ocx
      MYSQL_USER: root
      MYSQL_PASSWORD: NULL
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
      
  # octopusx domain service
  domain:
    container_name: octopusx_domain
    image: ekoopensource/octopusx-domain:v1.02
    depends_on:
      - data
    ports:
    - "5005:55502"