#you can access the endpoints using : http://localhost:9000

version: '3.6'
services:
  octopusx_data:
    container_name: octopusx_data
    image: ekoopensource/octopusx-data:v1.0
    ports:
      - "9000:55505"
    depends_on:
      - octopusx_db
    links:
      - octopusx_db:database

  # MySQL and document data store
  octopusx_db:
    container_name: octopusx_db
    image: mysql:5.7
    ports:
      - "30030:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: NULL
      MYSQL_DATABASE: ocx
      MYSQL_USER: root
      MYSQL_PASSWORD: NULL
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  console:
    image: ekoopensource/octopusx-console
    ports:
      - "5000:55500"
    env_file:
      - .env
  access:
    image: ekoopensource/octopusx-access:v1.01
    env_file:
      - .env
    ports:
      - "5001:55504"
  auth:
    image: ekoopensource/octopusx-auth
    ports:
    - "5002:55501"
  profile:
    image: ekoopensource/octopusx-profile
    ports:
    - "5003:55503"
  data:
    image: ekoopensource/octopusx-data:v1.0
    ports:
    - "5004:55505"
  domain:
    image: ekoopensource/octopusx-domain:v1.0
    env_file:
      - .env
    ports:
    - "5005:55502"
  # base:
  #   image: ekoopensource/octopusx-base
  #   ports:
  #     - "5006:55506"