version: '3'
services:
  console:
    image: ekoopensource/octopusx-console
    ports:
      - "5000:55500"
    env_file:
      - .env
  access:
    image: ekoopensource/octopusx-access:v1.01
    env_file:
      - .env
    ports:
      - "5001:55504"
  auth:
    image: ekoopensource/octopusx-auth
    ports:
    - "5002:55501"
  profile:
    image: ekoopensource/octopusx-profile
    ports:
    - "5003:55503"
  data:
    image: ekoopensource/octopusx-data:v1.0
    ports:
    - "5004:55505"
  domain:
    image: ekoopensource/octopusx-domain:v1.0
    env_file:
      - .env
    ports:
    - "5005:55502"
  # base:
  #   image: ekoopensource/octopusx-base
  #   ports:
  #     - "5006:55506"